// <auto-generated />
using System;
using Fptu.Pgs.ReviewScore.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fptu.Pgs.ReviewScore.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ReviewScoreDbContext))]
    [Migration("20260625020535_InitialReviewScore")]
    partial class InitialReviewScore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("score")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fptu.Pgs.ReviewScore.Api.Domain.CriterionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiFeedback")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("AiScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("SubmissionScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherFeedback")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("TeacherScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionScoreId", "CriterionId")
                        .IsUnique();

                    b.ToTable("CriterionScores", "score");
                });

            modelBuilder.Entity("Fptu.Pgs.ReviewScore.Api.Domain.ScoreAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("NewScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("OldScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("SubmissionScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionScoreId", "OccurredAtUtc");

                    b.ToTable("ScoreAuditLogs", "score");
                });

            modelBuilder.Entity("Fptu.Pgs.ReviewScore.Api.Domain.SubmissionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AiConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("AiFeedback")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("AiGradedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AiGradingResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AiScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FinalScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTimeOffset?>("FinalizedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FinalizedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TeacherFeedback")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset?>("TeacherGradedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TeacherScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("AiGradingResultId")
                        .IsUnique();

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("SubmissionScores", "score");
                });

            modelBuilder.Entity("Fptu.Pgs.ReviewScore.Api.Domain.CriterionScore", b =>
                {
                    b.HasOne("Fptu.Pgs.ReviewScore.Api.Domain.SubmissionScore", "SubmissionScore")
                        .WithMany("Criteria")
                        .HasForeignKey("SubmissionScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionScore");
                });

            modelBuilder.Entity("Fptu.Pgs.ReviewScore.Api.Domain.ScoreAuditLog", b =>
                {
                    b.HasOne("Fptu.Pgs.ReviewScore.Api.Domain.SubmissionScore", "SubmissionScore")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SubmissionScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubmissionScore");
                });

            modelBuilder.Entity("Fptu.Pgs.ReviewScore.Api.Domain.SubmissionScore", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
