using Fptu.Pgs.Contracts;

namespace Fptu.Pgs.AiGrading.Api.Providers;

public sealed class MockGradingProvider : IGradingProvider
{
    public string Name => "Mock";

    public Task<ProviderGradingResult> GradeAsync(
        GradeSubmissionRequest request,
        GradingProviderContext context,
        CancellationToken cancellationToken)
    {
        var text = request.ExtractedText ?? string.Empty;
        var criteria = request.Criteria
            .Select(criterion =>
            {
                var keywords = criterion.Name
                    .Split(' ', StringSplitOptions.RemoveEmptyEntries)
                    .Where(word => word.Length >= 4)
                    .ToArray();
                var matched = keywords.Count(keyword =>
                    text.Contains(keyword, StringComparison.OrdinalIgnoreCase));
                var ratio = keywords.Length == 0
                    ? (string.IsNullOrWhiteSpace(text) ? 0m : 0.5m)
                    : Math.Min(1m, (decimal)matched / keywords.Length);
                var score = decimal.Round(criterion.MaxScore * ratio, 2);

                return new ProviderCriterionGrade(
                    criterion.CriterionId,
                    criterion.Name,
                    criterion.MaxScore,
                    score,
                    ratio > 0
                        ? [$"Mock provider found {matched}/{keywords.Length} rubric keywords."]
                        : [],
                    ratio < 1 ? ["The mock provider could not verify all rubric requirements."] : [],
                    "Mock result for local development. Configure Gemini for real grading.",
                    ratio > 0 ? 0.5m : 0.2m);
            })
            .ToArray();

        var result = new ProviderGradingResult(
            criteria.Sum(x => x.AwardedScore),
            criteria.Sum(x => x.MaxScore),
            "This score was generated by the mock provider and must not be used as a real grade.",
            criteria.Length == 0 ? 0m : criteria.Average(x => x.Confidence),
            Name,
            "deterministic-mock-v1",
            "None",
            criteria);

        return Task.FromResult(result);
    }
}
